name: Main-Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - 
        name: Yarn
        run: yarn
      - 
        name: Unit/Integration Test
        run: yarn test
      - 
        name: Lint Test
        run: yarn lint
      - 
        name: Expo doctor
        run: yarn run expo doctor 
