name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v2
      - 
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - 
        name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - 
        name: Yarn
        run: yarn install
      - 
        name: Expo Publish
        run: expo publish
        env:
          NODE_OPTIONS: --max_old_space_size=8192
